### ISSUE TITLE
[1.7.10] Debug Hotkeys (F3 combinations) don't work with KeyCombs installed

### ISSUE THREAD

**Issue by DracoScythem** [AustereTony-MCMods/Key-Combinations#1]
With KeyCombinations installed all F3 based debug functions (F3+A to reload chunks e.g.) become inaccessible (the input is registered as 2 independent keystrokes ("open debug overlay and strife left"), not as a combination ("open debug overlay and reload all chunks").
This also affects ReBind.
MC: 1.7.10
Versions: 1.1.1 [latest] (KeyCombinations) / 2.7.0 [latest] (ReBind)

If you need more information, please don't hesitate to ask :)

**Comment by AustereTony-MCMods** [comment]
You helped me a lot. Should be fixed in 1.1.2 for Key Combinations (1.6.4, 1.7.10, 1.8.9) and in 2.7.2 for ReBind (1.7.10, 1.8.9). Check it out, it will be available on Curse in few hours. Thank you.

**Comment by AustereTony-MCMods** [comment]
Consider is fixed.
